printWidth: 80
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
arrowParens: avoid

# svelte rules:
svelteSortOrder: styles-scripts-markup
svelteStrictMode: true
svelteBracketNewLine: true
svelteAllowShorthand: true
