printWidth: 80
tabWidth: 4
useTabs: true
semi: false
singleQuote: true
arrowParens: avoid

# svelte rules:
svelteSortOrder: options-scripts-styles-markup
svelteStrictMode: true
svelteBracketNewLine: true
svelteAllowShorthand: true
